"""LLM-to-LLM voice simulation test infrastructure.

This package provides a framework for end-to-end simulation testing of the
Donna voice pipeline.  A "caller" LLM plays the role of an elderly senior
while the real pipeline (Observer -> Director -> Claude -> TTS) responds.

Key components:
- CallerAgent / CallerPersona / CallerGoal: Haiku-powered caller simulation
- CallerEvent / CallResult: structured output from a simulated call
- ResponseCollector: FrameProcessor that captures pipeline output
- CallerTransport: protocol for injecting speech and receiving responses
- TestSenior / seed_test_senior / cleanup_test_senior: DB fixtures for integration tests
"""

from tests.simulation.caller import (
    CallerAgent,
    CallerGoal,
    CallerPersona,
)
from tests.simulation.fixtures import (
    TestSenior,
    build_session_state,
    cleanup_test_senior,
    create_test_conversation,
    seed_test_senior,
)
from tests.simulation.scenarios import (
    LiveSimScenario,
    ambiguous_reminder_ack_scenario,
    async_search_overlap_scenario,
    cognitive_confusion_reminder_scenario,
    consent_ai_question_then_grant_scenario,
    consent_ambiguous_then_grant_scenario,
    consent_decline_scenario,
    consent_boundary_reminder_attempt_scenario,
    consent_grant_scenario,
    consent_mock_call_scenarios,
    consent_off_topic_redirect_decline_scenario,
    cognitive_confusion_scenario,
    discovery_boundary_redirect_scenario,
    discovery_correction_scenario,
    discovery_early_goodbye_scenario,
    discovery_first_call_correction_scenario,
    discovery_first_call_early_goodbye_scenario,
    discovery_first_call_quiet_preferences_scenario,
    discovery_first_call_scenario,
    discovery_first_call_weather_scenario,
    discovery_mock_call_scenarios,
    discovery_no_more_calls_scenario,
    discovery_not_good_time_scenario,
    discovery_off_topic_weather_scenario,
    discovery_quiet_routine_scenario,
    discovery_scenario,
    discovery_boundary_reminder_attempt_scenario,
    embedding_outage_scenario,
    empty_search_result_scenario,
    false_goodbye_scenario,
    false_goodbye_reminder_ack_scenario,
    health_concern_scenario,
    low_engagement_scenario,
    low_engagement_reminder_scenario,
    memory_recall_scenario,
    memory_seed_scenario,
    multiple_reminders_scenario,
    out_of_order_reminder_ack_scenario,
    reminder_interruption_scenario,
    reminder_overload_scenario,
    reminder_scenario,
    reminder_creation_scenario,
    search_phi_guard_scenario,
    similar_reminders_scenario,
    slow_search_overlap_scenario,
    unacknowledged_reminder_scenario,
    web_search_scenario,
)
from tests.simulation.pipeline import (
    LiveSimComponents,
    build_live_sim_pipeline,
)
from tests.simulation.runner import run_simulated_call
from tests.simulation.concurrent import (
    ConcurrentCallOutcome,
    ConcurrentCallSpec,
    ConcurrentRunSummary,
    run_simulated_calls_concurrent,
)
from tests.simulation.cohort import (
    DEFAULT_THRESHOLDS,
    CohortComparison,
    CohortSloReport,
    CohortSloThresholds,
    SloBreach,
    build_cohort_report,
    compare_cohorts,
)
from tests.simulation.stress import (
    STRESS_SCENARIO_FACTORIES,
    build_parallel_flake_specs,
    build_post_call_stampede_specs,
    build_reminder_stampede_specs,
    build_stress_pack_specs,
    scale_2000_load_test_plan,
)
from tests.simulation.transport import (
    AudioCallerTransport,
    CallerEvent,
    CallerTransport,
    CallResult,
    ResponseCollector,
    TextCallerTransport,
    TtsProvider,
    cartesia_tts_provider,
    elevenlabs_tts_provider,
    silence_tts_provider,
)

__all__ = [
    "AudioCallerTransport",
    "CallerAgent",
    "CallerGoal",
    "CallerPersona",
    "CallerEvent",
    "CallerTransport",
    "CallResult",
    "CohortComparison",
    "CohortSloReport",
    "CohortSloThresholds",
    "ConcurrentCallOutcome",
    "ConcurrentCallSpec",
    "ConcurrentRunSummary",
    "DEFAULT_THRESHOLDS",
    "LiveSimComponents",
    "LiveSimScenario",
    "ResponseCollector",
    "SloBreach",
    "STRESS_SCENARIO_FACTORIES",
    "TestSenior",
    "TextCallerTransport",
    "TtsProvider",
    "build_cohort_report",
    "cartesia_tts_provider",
    "elevenlabs_tts_provider",
    "silence_tts_provider",
    "build_live_sim_pipeline",
    "build_session_state",
    "cleanup_test_senior",
    "compare_cohorts",
    "create_test_conversation",
    "ambiguous_reminder_ack_scenario",
    "async_search_overlap_scenario",
    "build_parallel_flake_specs",
    "build_post_call_stampede_specs",
    "build_reminder_stampede_specs",
    "build_stress_pack_specs",
    "consent_ai_question_then_grant_scenario",
    "consent_ambiguous_then_grant_scenario",
    "consent_decline_scenario",
    "consent_boundary_reminder_attempt_scenario",
    "consent_grant_scenario",
    "consent_mock_call_scenarios",
    "consent_off_topic_redirect_decline_scenario",
    "cognitive_confusion_scenario",
    "cognitive_confusion_reminder_scenario",
    "discovery_boundary_redirect_scenario",
    "discovery_correction_scenario",
    "discovery_early_goodbye_scenario",
    "discovery_first_call_correction_scenario",
    "discovery_first_call_early_goodbye_scenario",
    "discovery_first_call_quiet_preferences_scenario",
    "discovery_first_call_scenario",
    "discovery_first_call_weather_scenario",
    "discovery_mock_call_scenarios",
    "discovery_no_more_calls_scenario",
    "discovery_not_good_time_scenario",
    "discovery_off_topic_weather_scenario",
    "discovery_quiet_routine_scenario",
    "discovery_scenario",
    "discovery_boundary_reminder_attempt_scenario",
    "embedding_outage_scenario",
    "empty_search_result_scenario",
    "false_goodbye_scenario",
    "false_goodbye_reminder_ack_scenario",
    "health_concern_scenario",
    "low_engagement_scenario",
    "low_engagement_reminder_scenario",
    "run_simulated_call",
    "run_simulated_calls_concurrent",
    "seed_test_senior",
    "memory_recall_scenario",
    "memory_seed_scenario",
    "multiple_reminders_scenario",
    "out_of_order_reminder_ack_scenario",
    "reminder_scenario",
    "reminder_creation_scenario",
    "reminder_interruption_scenario",
    "reminder_overload_scenario",
    "web_search_scenario",
    "scale_2000_load_test_plan",
    "search_phi_guard_scenario",
    "similar_reminders_scenario",
    "slow_search_overlap_scenario",
    "unacknowledged_reminder_scenario",
]
